language: python

python:
    - "3.3"
    - "3.4"

env:
    matrix:
        - MARKBOOK_SETTINGS=DevelopmentConfig
        - MARKBOOK_SETTINGS=ProductionConfig

install: "pip install -r requirements.txt"

script:  python setup.py test --pytest-args=tests
